### ISSUE TITLE
libcudart.so.11.0 error

### ISSUE THREAD

**Issue by huangtingwei9988** [AniZpZ/AutoSmoothQuant#15]
Hello! @AniZpZ Thanks for the nice work!  I use cuda-11.8, encounter this error:
<img width="656" alt="image" src="https://github.com/AniZpZ/AutoSmoothQuant/assets/141888744/6bd6431d-7feb-499d-8135-e2e02aed36a1">

`Traceback (most recent call last):
  File "/ossfs/node_40832759/workspace/AutoSmoothQuant/autosmoothquant/examples/smoothquant_model.py", line 13, in <module>
    from autosmoothquant.models import _MODEL_TYPE, _MODEL_REGISTRY, _CONFIG_REGISTRY
  File "/ossfs/node_40832759/workspace/AutoSmoothQuant/autosmoothquant/models/__init__.py", line 1, in <module>
    from .baichuan import Int8BaichuanForCausalLM
  File "/ossfs/node_40832759/workspace/AutoSmoothQuant/autosmoothquant/models/baichuan.py", line 9, in <module>
    from autosmoothquant.layers.nn.linear import W8A8BFP32OFP32LinearWithQuantScale, W8A8BFP32OFP32Linear, W8A8BFP32OFP32QKVLinear
  File "/ossfs/node_40832759/workspace/AutoSmoothQuant/autosmoothquant/layers/__init__.py", line 1, in <module>
    from . import nn
  File "/ossfs/node_40832759/workspace/AutoSmoothQuant/autosmoothquant/layers/nn/__init__.py", line 1, in <module>
    from .linear import W8A8BFP32OFP32Linear, W8A8BFP32OFP32QKVLinear, W8A8BFP32OFP32LinearWithQuantScale
  File "/ossfs/node_40832759/workspace/AutoSmoothQuant/autosmoothquant/layers/nn/linear.py", line 4, in <module>
    from autosmoothquant._CUDA import I8CUGEMM
ImportError: /ossfs/node_40832759/workspace/AutoSmoothQuant/autosmoothquant/_CUDA.cpython-38-x86_64-linux-gnu.so: symbol cudaOccupancyMaxActiveClusters, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
(base)`

**Comment by AniZpZ** [comment]
Hi! It seems that you have multiple versions of CUDA installed in your environment, and you are using different versions of it for compiling and running. You can try to check your LD_LIBRARY_PATH or use the ldd command to verify the lib.
